### ISSUE TITLE
filter rule not working 

### ISSUE THREAD

**Issue by HexagonTR** [twitterdev/ETL#1]
Hi, i was using this code since 3 months without problem but today noon time it is start to forward irrelevant tweets to spread sheet. 

my cons filter is 

const filter_rule = `(${search_term} OR #${search_hashtag}) has:links -is:retweet`

But forwarding retweets and irrelevant hashtags and tweets .

so far : 
I have changed bearer token  and reinstalled  still same...

Any advices are welcome .

**Comment by lagache** [comment]
Hi,
It could be that you have other rules set in the API bringing the tweets you don't want.
I'd start by making sure you have only the rule you want set in the API.
You can use the API Explorer to test that out: https://developer.twitter.com/apitools/api?endpoint=%2F2%2Ftweets%2Fsearch%2Fstream%2Frules&method=get (Simply copy the curl command at the bottom)

**Comment by HexagonTR** [comment]
Hi thanks for the reply, 

curl output like below : 

{"data":[{"id":"1504812407352348***","value":"(F*** OR #F***) has:links -is:retweet"},{"id":"15048192640159744**","value":"(F*** OR #F****) "},{"id":"15048276858428620**","value":"(F*** OR #F***) -is:retweet "}],"meta":{"sent":"2022-03-25T

looks like normal I think,(I placed asterisk btw)

Thanks again,

**Comment by lagache** [comment]
The 2nd rule (15048192640159744) doesn't check -is:retweet, that could explain you get retweets in the stream.
It's in the stream if it matches at least 1 rule: Rule1 OR Rule2 OR Rule3.
Also F*** does a contain F*** filter. If you want only the exact word match, you need to use "F***".

I recommend to delete all your rules and recreate just one `("F***" OR #F***) has:links -is:retweet`
Delete rules curl:
`curl -X POST "https://api.twitter.com/2/tweets/search/stream/rules" -H "Authorization: Bearer $BEARER_TOKEN" -H "Content-type: application/json" -d '{"delete":{"ids":["1504812407352348","15048192640159744","15048276858428620"]}}'`

**Comment by HexagonTR** [comment]
> The 2nd rule (15048192640159744) doesn't check -is:retweet, that could explain you get retweets in the stream. It's in the stream if it matches at least 1 rule: Rule1 OR Rule2 OR Rule3. Also F*** does a contain F*** filter. If you want only the exact word match, you need to use "F***".
> 
> I recommend to delete all your rules and recreate just one `("F***" OR #F***) has:links -is:retweet` Delete rules curl: `curl -X POST "https://api.twitter.com/2/tweets/search/stream/rules" -H "Authorization: Bearer $BEARER_TOKEN" -H "Content-type: application/json" -d '{"delete":{"ids":["1504812407352348","15048192640159744","15048276858428620"]}}'`

Thank you @lagache it is working normally now. I think npm start and stops causing filter rule duplicates. I have deleted the all rules and let to the script create new one . 


Best wishes, 

Hex.
